BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    BoxLayout:
        orientation: 'horizontal'
        spacing: 10
        size_hint_y: 0.7

        TextInput:
            id: input_number
            hint_text: 'Enter a number'
            size_hint_x: 0.7

        Button:
            text: 'Square'
            size_hint_x: 0.3
            on_press: app.handle_calculate(input_number.text)

    Label:
        id: output_label
        text: 'Enter a number and press "Square"'
        color: (1, 0.41, 0.71, 1)  # Pink